server {
  listen 80;
  root /usr/share/nginx/html;
  location = /config.json { add_header Cache-Control "no-store"; }
  location /embed/ { add_header Access-Control-Allow-Origin "*"; }
  location / { try_files $uri /index.html; }
}
